name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Change this to your default branch if different.

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Specify the Go version

    - name: Set up Hugo (Extended version)
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.117.0'  # Specify Hugo extended version
        extended: true

    # Skip caching for now if there's no go.sum
    # - name: Cache Go modules
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-

    - name: Install Go dependencies
      run: go mod tidy  # Ensure go.mod and go.sum are up to date

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
